{% set name = "midas2" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/4b/ae/601fdd774eda776d310a927ddb0cca2e445a2a53643f09f29aa33d380399/midas2-1.1.0.tar.gz
  sha256: d58e9b9d4ccc765e400e982392b0b0a7bfff2ae7898cf9002689382cc53717be
  #git_url: https://github.com/czbiohub/MIDAS2.0.git
  #git_rev: v1.1.0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-dependencies

requirements:
  host:
    - python >=3.9,<3.10
    - pip
    - setuptools
  run:
    - python >=3.9,<3.10
    - tbb ==2021.10.0
    - numpy >=1.25.2
    - biopython >=1.81
    - gffutils >=0.12
    - bowtie2 >=2.5.1
    - samtools >=1.17
    - pysam >=0.21.0
    - hs-blastn ==0.0.5
    - blast >=2.14.0
    - awscli
    - lz4
    - prokka >=1.14.6
    - vsearch >=2.23.0
    - seqkit >=2.5.1
    - cd-hit >=4.8.1

test:
  imports:
    - midas2
  commands:
    - midas2 --version
    - midas2 run_snps --help

about:
  home: "https://github.com/czbiohub/MIDAS2"
  license: MIT License
  license_family: MIT
  summary: "Metagenomic Intra-Species Diversity Analysis 2"
